// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/auth-context";
import { Toaster } from "@/components/ui/sonner";
import { ErrorBoundary } from "@/components/ui/error-boundary";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  metadataBase: new URL("https://brinde.ai"),
  title: {
    default: "Brinde.AI - Jogos de Bebida Inteligentes com IA",
    template: "%s | Brinde.AI",
  },
  description: "A plataforma definitiva para jogos de bebida e drinks personalizados com IA. Mais de 10 jogos épicos, receitas inteligentes e diversão garantida.",
  keywords: [
    "jogos de bebida",
    "drinks",
    "IA",
    "festas",
    "receitas",
    "brinde",
    "diversão",
    "roleta bebada",
    "batata quente",
    "eu nunca",
    "verdade ou shot",
    "drinks personalizados",
    "inteligência artificial",
  ],
  authors: [{ name: "Brinde.AI", url: "https://brinde.ai" }],
  creator: "Brinde.AI",
  publisher: "Brinde.AI",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "pt_BR",
    url: "https://brinde.ai",
    title: "Brinde.AI - Jogos de Bebida Inteligentes",
    description: "Transforme suas festas em experiências inesquecíveis com jogos de bebida e drinks personalizados por IA",
    siteName: "Brinde.AI",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Brinde.AI - Jogos de Bebida Inteligentes",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Brinde.AI - Jogos de Bebida Inteligentes",
    description: "Transforme suas festas em experiências inesquecíveis",
    images: ["/og-image.png"],
    creator: "@brindeai",
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#0D0D0D" },
    { media: "(prefers-color-scheme: light)", color: "#0D0D0D" },
  ],
  alternates: {
    canonical: "https://brinde.ai",
  },
  verification: {
    google: "your-google-verification-code",
  },
  category: "entertainment",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="canonical" href="https://brinde.ai" />
        
        {/* Structured Data for SEO */}
        <script
          id="structured-data"
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebApplication",
              name: "Brinde.AI",
              description: "A plataforma definitiva para jogos de bebida inteligentes com IA",
              url: "https://brinde.ai",
              applicationCategory: "EntertainmentApplication",
              operatingSystem: "Any",
              offers: {
                "@type": "Offer",
                price: "0",
                priceCurrency: "BRL",
              },
              aggregateRating: {
                "@type": "AggregateRating",
                ratingValue: "4.9",
                ratingCount: "50000",
              },
            }),
          }}
        />
      </head>
      <body className={`${inter.variable} font-inter antialiased`}>
        <ErrorBoundary>
          <AuthProvider>
            {children}
            <Toaster 
              position="top-right" 
              richColors 
              closeButton
              duration={4000}
              toastOptions={{
                style: {
                  background: "rgba(255, 255, 255, 0.1)",
                  backdropFilter: "blur(10px)",
                  border: "1px solid rgba(255, 255, 255, 0.2)",
                  color: "white",
                },
              }}
            />
          </AuthProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
